Added column name swap and test for column names
dramanica/geograph pull request #10
Opened 2023-12-06 23:53 UTC by AramishFatima

2023-12-12 10:18 UTC, dramanica requested changes
This does the job. But could you please have a go at also dealing with more labels?

2023-12-12 10:18 UTC, dramanica commented on R/classes.R
> +    if (identical(colnames(input$coords), c("lat", "lon"))) {
This is great. But could we add another couple of options. The main labels are 'latitude', 'lat' and 'y'. If you pass those labels to tolower(), you can then catch various capitalised versions.

2023-12-19 00:24 UTC, AramishFatima commented on R/classes.R
> +    if (identical(colnames(input$coords), c("lat", "lon"))) {
I think I have added this now

2023-12-19 13:20 UTC, dramanica approved these changes

2023-12-19 13:20 UTC, merged